import type { Metadata } from 'next';
import './globals.css';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Venus Marketplace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
